#!/bin/bash

if [ $# -ge 1 ]; then
	CMD="$@"
	docker run $FLAGS -v $PWD:/home/dev ilab-docker:min bash -c "$CMD"
else
	# Default to shell if no commands are given.
	docker run -t -i -v $PWD:/home/dev ilab-docker:min
fi
