#!/bin/bash

if [ $# -ge 1 ]; then
	CMD="$@"
	docker run -i -v $PWD:/home/dev wlynch/ilab bash -c "$CMD"
else
	# Default to shell if no commands are given.
	docker run -t -i -v $PWD:/home/dev wlynch/ilab
fi
